
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 22 19:39:53 CDT 2015
//----------------------------------------------------

package project;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMG = 9;
  public static final int SEMI = 2;
  public static final int PLAYER = 5;
  public static final int POS = 12;
  public static final int ID = 15;
  public static final int OBJECT = 7;
  public static final int DEL = 13;
  public static final int BKG = 8;
  public static final int EOF = 0;
  public static final int PAR = 17;
  public static final int ENEMY = 6;
  public static final int DIR = 16;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ASSIGN = 4;
  public static final int HP = 11;
  public static final int ENTERO = 14;
  public static final int ATK = 10;
}

